use_frameworks!

platform :ios, '8.0'

target 'MTLockDeviceKit_Example' do
  pod 'MTLockDeviceKit', :path => '../'

  target 'MTLockDeviceKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
